"""Scan 106 edits to deliverables/main.tex: clause-join rates down to the corpus3 range and the
orphaned post-hoc reading of rule one removed. Each pair must match exactly once."""
from pathlib import Path
P = Path(__file__).resolve().parents[2] / "deliverables" / "main.tex"
E = [
# abstract
("usually sum per-benchmark variances, which ignores covariance between benchmarks across training runs.",
 "usually sum per-benchmark variances and ignore the covariance between benchmarks across training runs."),
("times its value under independence, so a comparison that assumes independence at a nominal 0.05 has a true size near 0.11.",
 "times its value under independence. A comparison that assumes independence at a nominal 0.05 therefore has a true size near 0.11."),
("net of item noise, and the correction changes few of DataDecide's recipe orderings.",
 "net of item noise. Correcting for the covariance changes few of DataDecide's recipe orderings."),
("give margin inflation of \\res{r1lam}{R1 lambda} with interval \\ci{\\res{r1lo}{lo}}{\\res{r1hi}{hi}}, which includes one.}",
 "give margin inflation of \\res{r1lam}{R1 lambda} with an interval \\ci{\\res{r1lo}{lo}}{\\res{r1hi}{hi}} that includes one.}"),
("A disjoint item bank leaves \\res{xlam}{cross lambda} there, which gives no support to a shared item explanation.",
 "A disjoint item bank leaves \\res{xlam}{cross lambda} there and gives no support to a shared item explanation."),
("We recommend reporting the replicate standard deviation of the battery average, which gives 1.237 here without an item split, together with a benchmark-removal check.",
 "We recommend reporting the replicate standard deviation of the battery average together with a benchmark-removal check, and that standard deviation needs no item split and gives an inflation of 1.237 here."),
# introduction
("with $\\Phi$ the standard normal distribution function, which is 0.115 at our margin estimate, and our simulation",
 "with $\\Phi$ the standard normal distribution function. That size is 0.115 at our margin estimate, and our simulation"),
("On DataDecide's recipe comparisons the correction changes few calls (Section~\\ref{sec:prediction}), so the understatement shows mainly",
 "Because the correction changes few calls on DataDecide's recipe comparisons (Section~\\ref{sec:prediction}), the understatement shows mainly"),
("Margins carry more seed signal, with per-benchmark reliability averaging 0.652 against 0.324 for accuracy (run variance's share of a benchmark half's replicate variance; Section~\\ref{sec:composition}), so we treat margins as the primary scale and accuracy as a bound.",
 "Margins carry more seed signal, with per-benchmark reliability, the run variance's share of a benchmark half's replicate variance, averaging 0.652 against 0.324 for accuracy (Section~\\ref{sec:composition}). We therefore treat margins as the primary scale and accuracy as a bound."),
# estimator
("stop at 25 percent of the 1B compute budget, which adds a batch component beyond the seed.",
 "stop at 25 percent of the 1B compute budget. That schedule difference adds a batch component beyond the seed."),
("run effects within a configuration, which Section~\\ref{sec:data} shows the released runs only approximate, and we write",
 "run effects within a configuration, an assumption the released runs only approximate (Section~\\ref{sec:data}), and we write"),
("This target is defined for a redrawn or extended item bank, while a run's item-specific deviations on the released bank fall into $\\varepsilon$, so reproducibility on that fixed bank is a separate question.",
 "This target is defined for a redrawn or extended item bank. A run's item-specific deviations on the released bank fall into $\\varepsilon$, and reproducibility on that fixed bank is a separate question."),
("Centring removes item effects constant across runs.",
 "Centring removes any item effect that stays constant across runs."),
("Cross-format inflation, which keeps only the diagonal and the covariances between benchmarks of different scoring formats, is 0.921",
 "Cross-format inflation keeps only the diagonal and the covariances between benchmarks of different scoring formats, and it is 0.921"),
("negative cross-format run covariance, which the 0.921 point estimate suggests, could offset",
 "negative cross-format run covariance, as the 0.921 point estimate suggests, could offset"),
("needs no halves and no cross-half assumption, so only the split's redrawn-bank target and the per-benchmark run variances rest on it.",
 "needs no halves and no cross-half assumption. Only the split's redrawn-bank target and the per-benchmark run variances rest on it."),
("We sum each across configurations before dividing, which gives",
 "We sum each across configurations before dividing to obtain"),
("Its denominator sums per-benchmark replicate variances, so any item component the halves share counts as fixed-bank run variance.",
 "Its denominator sums per-benchmark replicate variances, and any item component the halves share therefore counts as fixed-bank run variance."),
("and 0.186 of the accuracy one, and the two targets nearly coincide, while",
 "and 0.186 of the accuracy one, leaving the two targets nearly equal, while"),
("using 4,999 Rademacher draws, a linearisation of the squared ratio, and the observed denominator held fixed during resampling",
 "using 4,999 Rademacher draws and a linearisation of the squared ratio, with the observed denominator held fixed during resampling"),
("bias the estimate down by 0.011 to 0.016, so in these populations finite-sample bias works against finding an excess.",
 "bias the estimate down by 0.011 to 0.016. Finite-sample bias in these populations therefore works against finding an excess."),
# data
("at the selected steps, and the auxiliary-run contrast (1.256 in Table~\\ref{tab:primary}) removes the batch component.",
 "at the selected steps, while the auxiliary-run contrast (1.256 in Table~\\ref{tab:primary}) removes the batch component."),
("That check can't see an offset shared by every configuration, and the auxiliary contrast doesn't remove differences tied to checkpoint schedules, which the PolyPythias seeds avoid by sharing one final step (Section~\\ref{sec:family}).",
 "That check can't see an offset shared by every configuration. The auxiliary contrast doesn't remove differences tied to checkpoint schedules either, and the PolyPythias seeds avoid them by sharing one final step (Section~\\ref{sec:family})."),
("We never drew the analysis plan's split of screening and estimation recipes, so every choice in the primary analysis could see all 125 configurations,",
 "We never drew the analysis plan's split of screening and estimation recipes. Every choice in the primary analysis could therefore see all 125 configurations,"),
("from the DataDecide release, so every prompt matches its scoring byte for byte.",
 "from the DataDecide release, and every prompt matches its scoring byte for byte."),
# results
("more than the numerator, which raises the factor while the margin aggregate standard deviation falls",
 "more than the numerator and so raises the factor, while the margin aggregate standard deviation falls"),
("0.002 below accuracy, so item-level sharing accounts for little of either,",
 "0.002 below accuracy. Item-level sharing thus accounts for little of either,"),
("On margins every removal leaves an interval that excludes one, and the estimate runs from 1.096",
 "On margins every removal leaves an interval that excludes one, with estimates from 1.096"),
("Inflation belongs to its battery, so the four-task and ten-task values aren't directly comparable, and the held-out interval is 0.626 wide",
 "Because inflation belongs to its battery, the four-task and ten-task values aren't directly comparable. The held-out interval is also 0.626 wide"),
("while the margin interval doesn't, so which scale's interval excludes one depends on the battery.",
 "while the margin interval doesn't, the reverse of the original battery's pattern on the same runs."),
("excludes one, so the held-out estimate depends on battery composition as the original does",
 "excludes one. The held-out estimate thus depends on battery composition as the original does"),
("on the same runs, which removes any component the halves share only through a common item set.",
 "on the same runs, and that assignment removes any component the halves share only through a common item set."),
("which pretraining data are more likely to contain, so any covariance these differences carry also enters the cross-bank estimate.",
 "which pretraining data are more likely to contain. Any covariance these differences carry also enters the cross-bank estimate."),
("At a share of 0.755, which alone gives 1.244 on this noise,",
 "At a share of 0.755, enough alone to give 1.244 on this noise,"),
("undecided in 0.919, so an undecided verdict can't exclude one. A first-rule pass confirms within-bank inflation in this family. In an exploratory reading we added after fixing that rule, a failing estimate at or above 1.026, the 5th percentile of estimates at a true 1.244, is read only through its jackknife upper limit, which bounds inflation in this family. Under independence the middle 90\\% of estimates runs from 0.848 to 1.139, which extends past 1.026, so the estimate alone can't separate transfer from independence. A failing estimate below 1.026 counts against transfer.",
 "undecided in 0.919. An undecided verdict therefore can't exclude one."),
("Each PolyPythias seed reruns one recipe, which leaves no counterpart to the batch component behind our auxiliary contrast.",
 "Each PolyPythias seed reruns one recipe, and no counterpart arises to the batch component behind our auxiliary contrast."),
("with jackknife interval \\ci{\\res{r1lo}{lo}}{\\res{r1hi}{hi}}, which includes one, and accuracy gives",
 "with a jackknife interval \\ci{\\res{r1lo}{lo}}{\\res{r1hi}{hi}} that includes one, and accuracy gives"),
("against 250 in DataDecide, so the interval can't separate this family's inflation from one or from DataDecide's 1.244.",
 "against 250 in DataDecide, too few for the interval to separate this family's inflation from one or from DataDecide's 1.244."),
("\\ci{\\res{xlo}{lo}}{\\res{xhi}{hi}}, and the within-minus-cross difference in log squared inflation has interval \\ci{\\res{dlo}{lo}}{\\res{dhi}{hi}}, which includes zero, so its upper limit bounds",
 "\\ci{\\res{xlo}{lo}}{\\res{xhi}{hi}}, while the within-minus-cross difference in log squared inflation has an interval \\ci{\\res{dlo}{lo}}{\\res{dhi}{hi}} that includes zero, and its upper limit then bounds"),
("\\ci{\\res{xlo}{lo}}{\\res{xhi}{hi}}, which covers one, and the within-minus-cross difference in log squared inflation has interval \\ci{\\res{dlo}{lo}}{\\res{dhi}{hi}}, which lies above zero.",
 "\\ci{\\res{xlo}{lo}}{\\res{xhi}{hi}} covering one, while the within-minus-cross difference in log squared inflation has an interval \\ci{\\res{dlo}{lo}}{\\res{dhi}{hi}} lying above zero."),
("or from differences between the banks, and the cross-bank value of \\res{xlam}{cross lambda} is the one",
 "or from differences between the banks. The cross-bank value of \\res{xlam}{cross lambda} is the one"),
("\\ci{\\res{xlo}{lo}}{\\res{xhi}{hi}}, and the within-minus-cross difference in log squared inflation has interval \\ci{\\res{dlo}{lo}}{\\res{dhi}{hi}}. Bank two holds under a fifth of bank one's items, which widens both intervals.}",
 "\\ci{\\res{xlo}{lo}}{\\res{xhi}{hi}}, while the within-minus-cross difference in log squared inflation has interval \\ci{\\res{dlo}{lo}}{\\res{dhi}{hi}}. Bank two holds under a fifth of bank one's items, and that smaller bank widens both intervals.}"),
("Format and task content aren't separable here.",
 "Format and task content aren't separable in this battery."),
("calls on such pairs, which changes the share of wrong calls by at most 0.009,",
 "calls on such pairs and changes the share of wrong calls by at most 0.009,"),
("genuine rank changes between sizes, so these rates aren't false-positive rates",
 "genuine rank changes between sizes, and these rates therefore aren't false-positive rates"),
("every interval reaching zero, and the ratio of seed-matched to seed-unmatched paired-difference standard deviations runs from 0.928 to 1.025, which gives no sign",
 "every interval reaching zero. The ratio of seed-matched to seed-unmatched paired-difference standard deviations runs from 0.928 to 1.025 and gives no sign"),
# related work and discussion
("across shifted ImageNet test sets, which our accuracy interval allows,",
 "across shifted ImageNet test sets, a pattern our accuracy interval allows,"),
("resample runs within a task, which discards the paired run effects we keep.",
 "resample runs within a task and discard the paired run effects we keep."),
("at the scored checkpoint, which leaves independence open, and at accuracy-like",
 "at the scored checkpoint that leaves independence open, and at accuracy-like"),
("Apart from the pre-specified test, which failed at its protocol scope, and the two PolyPythias rules fixed before scoring, our study remains exploratory.",
 "Apart from the held-out test and the two PolyPythias rules, all fixed before scoring, our study remains exploratory."),
("on the second bank, which leaves the 1.244 untested on fresh items and the shared-item check unrun in the family that supplies our headline.",
 "on the second bank. The 1.244 thus stays untested on fresh items, and the shared-item check is unrun in the family that supplies our headline."),
("on average, and the 33 configurations that share a final step give",
 "on average, while the 33 configurations that share a final step give"),
("finds such a component in one family, so the within-bank value can overstate run covariance there.",
 "finds such a component in one family, where the within-bank value can therefore overstate run covariance."),
]
s = P.read_text()
for a, b in E:
    n = s.count(a)
    assert n == 1, (n, a[:80])
    s = s.replace(a, b)
P.write_text(s)
print(len(E), "edits applied")
