"""Remove every 'rather than' from the extended supplement (user rule) with contractions and no new numbers.
usage: python3 work/goal/edits_rt_supp.py [--apply]"""
import sys
from pathlib import Path

P = Path(__file__).resolve().parents[2] / "deliverables" / "supplement_extended_body.tex"
E = [
    ("begin at 150M rather than 4M.", "begin at 150M, and DataDecide's smallest size is 4M."),
    ("We retain the original planning calculations rather than calculating power from the estimated effect after observing the results.",
     "We retain the original planning calculations and don't recompute power from the effect we estimated after we saw the results."),
    ("so they combine changes in checkpoint performance rather than isolating within-configuration seed deviations.",
     "so they mix changes in checkpoint performance with within-configuration seed deviations and can't isolate the latter."),
    ("which places replication across models rather than training seeds.", "which places replication across models and never across training seeds."),
    ("which counts variation between different models rather than the run-to-run covariance at a fixed configuration that our effective count describes.",
     "which counts variation between different models, while our effective count describes the run-to-run covariance at a fixed configuration."),
    ("Those ability structures describe performance differences rather than the within-configuration noise covariance estimated here.",
     "Those ability structures describe performance differences, a separate quantity from the within-configuration noise covariance we estimate here."),
    ("per-run reductions, rather than the original pipeline.", "per-run reductions outside the original pipeline."),
    ("We read this as the composition sensitivity reappearing at size resolution rather than as independent support for the pooled estimate, because",
     "We read this as the composition sensitivity again at size resolution, and we don't count it as independent support for the pooled estimate, because"),
    ("The transform is a device for keeping endpoints positive in a thin cell rather than a better interval (",
     "The transform keeps endpoints positive in a thin cell and doesn't give a better interval ("),
    ("Simulation says these per-size rows should be read as estimates with wide uncertainty rather than as intervals carrying their nominal level.",
     "Simulation says a reader should take these per-size rows as estimates with wide uncertainty, since their intervals don't carry their nominal level."),
    ("The shortfall is a sample size problem rather than a flaw in the interval.",
     "The shortfall comes from the small sample, and the interval construction itself has no flaw."),
    ("Those bands describe simulated estimator dispersion rather than confidence-interval coverage.",
     "Those bands describe simulated estimator dispersion and make no claim about confidence-interval coverage."),
    ("and therefore describe sensitivity rather than a zero-correlation null.", "and therefore describe sensitivity, and neither of them is a zero-correlation null."),
    ("Every interval is a 2.5 to 97.5 percentile range rather than a standard error, and no endpoint here is missing",
     "Every interval here is a 2.5 to 97.5 percentile range, and no endpoint is missing"),
    ("The accuracy conclusion is therefore a knife edge in the weighting rather than in the estimate, which moves smoothly, since",
     "The accuracy conclusion therefore sits on a knife edge in the weighting, while the estimate itself moves smoothly, since"),
    ("the nine-trait reference is 1.219 rather than the ten-trait 1.244", "the nine-trait reference is 1.219 against the ten-trait 1.244"),
    ("We simulated that question directly rather than arguing it.", "We simulated that question directly and didn't settle it by argument."),
    ("so what looks like movement is the simulation rather than the design.", "so the apparent movement is Monte Carlo noise from the simulation."),
    ("Power is the thing that additional runs actually buy here.", "The additional runs buy power here, and the gain is large."),
    ("The correction fixes the error rate rather than the sample size.", "The correction fixes the error rate, and only a larger sample fixes the power."),
    ("The extra accuracy runs therefore pay for the normal approximation rather than for the estimated correction.",
     "The extra accuracy runs therefore pay for the normal approximation, and the estimated correction doesn't add to them."),
    ("Below that it turns conservative rather than wrong, declaring in 0.015", "Below that it turns conservative, which is the safe direction, and declares in 0.015"),
    ("What transfers is the procedure rather than the number.", "A practitioner can transfer our procedure to another battery, but our number doesn't transfer with it."),
    ("The penalty is therefore governed by the distance between the two ratios rather than by which design produced the number.",
     "The distance between the two ratios therefore sets the penalty, and the design that produced the number doesn't matter."),
    ("That window is narrow enough that we recommend measuring rather than borrowing.",
     "That window is so narrow that we recommend that each practitioner measure the ratio on their own battery."),
    ("The DataDecide gap is 1,250 steps rather than 1,000.", "The DataDecide gap is 1,250 steps, against the 1,000 steps of the PolyPythias comparison."),
    ("It is the mildest of the four rather than a settled 0.940.", "It is the mildest of the four cells, and its coverage isn't a settled 0.940."),
    ("The shortfall we describe here is a property of the construction rather than of one set of draws.",
     "The shortfall we describe here belongs to the construction and doesn't come from one set of draws."),
    ("The inclusion of one is a property of the data rather than of the draws.", "The inclusion of one comes from the data and doesn't depend on the draws."),
    ("The shipped interval, which draws 4,999 times rather than 9,999, sits", "The shipped interval uses 4,999 draws in place of 9,999 and sits"),
    ("The violation breaks all three levels together rather than one of them, since", "The violation breaks all three levels together, since"),
    ("The eight that followed confirm it on the same generator family rather than test it independently.",
     "The eight cells that followed confirm it on the same generator family, so they aren't an independent test."),
    ("once its own miscalibration is corrected on these data, rather than through a construction chosen in simulation.",
     "when we correct its own miscalibration on these data, with no construction chosen in simulation."),
    ("We tested that explanation rather than leaving it as an argument.", "We tested that explanation directly and didn't leave it as an argument."),
    ("These figures give the contamination a reader would have to assume rather than a bound we established.",
     "These figures give the contamination a reader would have to assume, and they aren't a bound we established."),
    ("We therefore report that diagnostic as having no power rather than as a clean check.",
     "We therefore report that the diagnostic has no power, and we don't treat it as a clean check."),
    ("the main text quotes those ranges rather than the columns here", "the main text quotes those ranges in place of the columns here"),
    ("give a Monte Carlo value of $1/1001$, rather than zero.", "give a Monte Carlo value of $1/1001$, which is above zero."),
    ("versus conditional permutation populations, rather than establishing an error in the observed bootstrap scale.",
     "versus conditional permutation populations and doesn't establish an error in the observed bootstrap scale."),
    ("with HTTP 401 rather than 404, we read", "with HTTP 401 in place of 404, we read"),
    ("The obstacle we reported earlier was our own naming rather than access control.",
     "The obstacle we reported earlier came from our own naming, and access control played no part."),
    ("The configuration table requires the second-arm output rather than inspection of the DataDecide reduction alone.",
     "The configuration table requires the second-arm output, since an inspection of the DataDecide reduction alone isn't enough."),
    ("This compares predictions of one noisy realisation rather than of the underlying ratio.",
     "This comparison therefore tests predictions of one noisy realisation, and it can't test predictions of the underlying ratio."),
    ("that it assumes rather than measures.", "that it assumes and doesn't measure."),
    ("which is the cost of that lost direction rather than a change in the answer.", "which is the cost of that lost direction, and the answer itself doesn't change."),
    ("put the whole interval above one rather than below it, seven", "put the whole interval above one, seven"),
    ("We calibrated the count against a null rather than reading it directly.", "We calibrated the count against a null and didn't read it directly."),
    (", which is why we read them as a direction rather than as noise.", ", so we read them as a direction in the data."),
    ("as a statement about that battery rather than about accuracy in general.", "as a statement about that battery alone."),
    ("which is wider than the recipe interval rather than narrower.", "which is wider than the recipe interval."),
    ("The two-way interval is measurably worse here rather than merely no better, and", "The two-way interval is measurably worse here, and"),
    ("We checked that those labels mean what we take them to mean, rather than assuming it.",
     "We checked that those labels mean what we take them to mean, and we didn't assume it."),
    ("five of the eight recipes that resolve at 1B rather than all of them.", "five of the eight recipes that resolve at 1B, so three of them remain unchecked."),
    ("follows the size band rather than the recipe, built", "follows the size band in place of the recipe, built"),
    (", which is the recipe one rather than the band one.", ", which is the recipe channel."),
    ("Sweeping recipe sharing on the same scale confirms that the failure belongs to the cluster count rather than to the sharing, since",
     "A sweep of recipe sharing on the same scale confirms that the cluster count causes the failure, since"),
    ("A companion sweep varies the number of size bands rather than the runs, holding the cell count",
     "A companion sweep varies the number of size bands with the runs fixed, and it holds the cell count"),
    (" rather than anywhere near the accuracy battery's 1.45.", ", well above the accuracy battery's 1.45."),
    ("What breaks the estimator is the loudest band rather than the unevenness, because",
     "The loudest band breaks the estimator, and the unevenness alone doesn't, because"),
    ("The threshold rather than the spread is what a reader has to check.",
     "A reader therefore has to check the threshold, since the spread alone doesn't decide coverage."),
    ("that the previous sweep found rather than ask how uneven their bands are (", "that the previous sweep found, and they needn't ask how uneven their bands are ("),
    ("and removing six whole recipes rather than scattered cells leaves 0.945", "and the removal of six whole recipes in place of scattered cells leaves 0.945"),
    ("A further run draws the run count per configuration rather than fixing it.",
     "A further run draws the run count per configuration at random, and it doesn't fix that count."),
    ("and cutting whole recipes rather than scattered cells leaves 0.946 and 0.939.", "and cuts of whole recipes in place of scattered cells leave 0.946 and 0.939."),
    ("as uninformative rather than as independence (", "as uninformative, with no evidence for independence ("),
    ("The requirement is therefore joint rather than a recipe count on its own.", "The requirement is therefore joint, and no recipe count meets it on its own."),
    ("The shipped design sits well above the failure point rather than on it.", "The shipped design sits well above the failure point."),
    ("The extra clusters buy power rather than coverage, because", "The extra clusters buy power and leave coverage where it was, because"),
    ("should treat fifteen as their floor rather than ten.", "should treat fifteen recipes as their floor, and ten isn't enough."),
    ("recovers as the grid grows rather than as its own cluster count grows, since", "recovers as the grid grows, since"),
    ("Its failure came from thin clusters rather than from few ones.", "Its failure came from thin clusters, and the number of clusters played no part."),
    ("which is a curiosity rather than a recommendation, because", "which we report as a curiosity and don't recommend, because"),
    ("The weighting moves the quantity being estimated rather than the coverage of it, because",
     "The weighting changes the estimand and doesn't change its coverage, because"),
    ("The last question a reader will have is what the within-size evidence would have needed, and the answer is runs rather than cleverness.",
     "A reader may last ask what the within-size evidence would have needed, and the answer is more runs."),
    ("read through the shipped estimator rather than by hand.", "read through the shipped estimator with no step done by hand."),
    ("was a harmless simplification rather than a flattering one.", "was a harmless simplification, and it didn't flatter the results."),
    ("as evidence against a large ratio rather than as evidence for independence.", "as evidence against a large ratio, and it gives no evidence for independence."),
    ("what these data can resolve rather than as a confidence statement about the truth.",
     "what these data can resolve, and we don't read it as a confidence statement about the truth."),
    ("loses about half a point of coverage rather than the twelve points", "loses about half a point of coverage, against the twelve points"),
    ("is therefore a measurement rather than an artefact, since", "is therefore a real measurement, since"),
    ("The limitation transfers between the two scales rather than belonging to one of them.",
     "The limitation transfers between the two scales and doesn't belong to one of them."),
    ("The rule rather than the evidence therefore decided the swap, and", "The rule therefore decided the swap on its own, and"),
    ("which means shard order rather than any 1B number fixed the interim's recipe set.",
     "which means that shard order fixed the interim's recipe set, and no 1B number did."),
    ("uses the kernel's own split rather than the primary one.", "uses the kernel's own split in place of the primary one."),
]
t = P.read_text()
for old, new in E:
    n = t.count(old)
    if n != 1:
        sys.exit(f"expected one match, found {n}: {old[:80]}")
    t = t.replace(old, new)
if "--apply" in sys.argv:
    P.write_text(t)
print(f"{len(E)} edits {'applied' if '--apply' in sys.argv else 'checked'}; 'rather than' left: {t.count('rather than')}")
