"""ASD-STE100 rule 3.4 on the extended supplement: -ing verb forms become finite verbs or nouns, and the two
phrasal verbs go. Technical names (item-sampling, recipe-resampling, cross-fitting, prepivoting, residual
scaling, band-sharing, reinforcement learning) stay under STE 1.5.
usage: python3 work/goal/edits_ing_supp.py [--apply]"""
import sys
from pathlib import Path

P = Path(__file__).resolve().parents[2] / "deliverables" / "supplement_extended_body.tex"
E = [
    ("Excluding the 26 severely truncated configurations raises", "The exclusion of the 26 severely truncated configurations raises"),
    ("Permuting that share within each size over 4,999 draws gives", "A permutation of that share within each size over 4,999 draws gives"),
    ("We chose these subsets after seeing the full-sample estimates", "We chose these subsets after we saw the full-sample estimates"),
    ("proposed estimating reliability on eight screening recipes before inspecting seventeen", "proposed that we estimate reliability on eight screening recipes before we inspect seventeen"),
    ("Recomputing the per-trait information ratios gives", "A recomputation of the per-trait information ratios gives"),
    ("without releasing the ratios themselves", "although the summary didn't release the ratios themselves"),
    ("because multiplying a margin by a positive factor leaves its sign unchanged", "because a margin keeps its sign when we multiply it by a positive factor"),
    ("Partialling the gain covariate increases $\\Lambda_M$, and adding gain to the rank-one predictor worsens",
     "When we remove the gain covariate by partial regression, $\\Lambda_M$ increases, and the addition of gain to the rank-one predictor worsens"),
    ("seven rows, with transport and the auxiliary-run contrast supplying G6 and G8 separately.",
     "seven rows, and transport and the auxiliary-run contrast supply G6 and G8 separately."),
    ("records the outcomes without treating the document as verified preregistration.", "records the outcomes and doesn't treat the document as verified preregistration."),
    ("with its lower confidence limit also exceeding one.", "and its lower confidence limit also exceeds one."),
    ("compare four GLUE task rankings without estimating a covariance matrix.", "compare four GLUE task rankings, but they don't estimate a covariance matrix."),
    ("paired two-model comparisons, treating each evaluated model as fixed", "paired two-model comparisons and treats each evaluated model as fixed"),
    ("in their Appendix E.4 without estimating cross-task covariance.", "in their Appendix E.4, but they don't estimate cross-task covariance."),
    ("so we report both scales while retaining their separate noise properties", "so we report both scales and retain their separate noise properties"),
    ("advocate per-instance reporting alongside aggregate scores", "advocate per-instance reports alongside aggregate scores"),
    ("too small after accounting for judge and prompt variation", "too small once the analysis accounts for judge and prompt variation"),
    ("from covariance estimates, including diagonal entries", "from covariance estimates, diagonal entries included"),
    ("Substituting the reliability means in Table~\\ref{tab:original3}", "A substitution of the reliability means in Table~\\ref{tab:original3}"),
    ("for dependent effect sizes without requiring their complete covariance matrix", "for dependent effect sizes and don't require their complete covariance matrix"),
    ("with the maximum occurring for ARC-Easy and MMLU.", "and the maximum is for ARC-Easy and MMLU."),
    ("before clipping its negative eigenvalue and 3.62 after clipping", "before we clip its negative eigenvalue and 3.62 after the clip"),
    ("as the benchmark pulling hardest toward one.", "as the benchmark that pulls hardest toward one."),
    ("so it buys definedness by paying coverage", "so it buys definedness with coverage"),
    ("agree instead, covering within 0.006 of each other", "agree instead, and their coverage falls within 0.006 of each other"),
    ("improves on either, holding 0.954 at the corner", "improves on either, and it holds 0.954 at the corner"),
    ("division by $s_j$, clipping at $\\pm s_j$ before that division", "division by $s_j$, a clip at $\\pm s_j$ before that division"),
    ("Multiplying every margin by ten leaves", "A multiplication of every margin by ten leaves"),
    ("Bounding the margins of the same runs therefore reproduces", "Bounded margins of the same runs therefore reproduce"),
    ("while holding trait standard deviations fixed", "and holds trait standard deviations fixed"),
    ("Before fitting any model we clip", "Before we fit any model, we clip"),
    ("Before computing any contrast, we fixed", "Before we computed any contrast, we fixed"),
    ("bounds detectable gains without calibrating the ranking above.", "bounds detectable gains but doesn't calibrate the ranking above."),
    ("Removing each recipe in turn gives margin estimates", "The removal of each recipe in turn gives margin estimates"),
    ("Removing each size gives ranges", "The removal of each size gives ranges"),
    ("Excluding BoolQ gives 1.786 with", "Without BoolQ the estimate is 1.786 with"),
    ("Excluding CommonsenseQA gives the smallest", "The exclusion of CommonsenseQA gives the smallest"),
    ("the off-diagonal terms involving BoolQ sum", "the off-diagonal terms with BoolQ sum"),
    ("Removing WinoGrande is the only other removal whose accuracy interval, 1.023 to 1.178, excludes one,",
     "WinoGrande is the only other benchmark whose removal gives an accuracy interval that excludes one, at 1.023 to 1.178,"),
    ("lowering BoolQ's weight below the flat tenth in seven steps to 0.0533 while raising the other nine weights together to keep the battery summing to one",
     "where we lowered BoolQ's weight below the flat tenth in seven steps to 0.0533 and raised the other nine weights together so that the weights sum to one"),
    ("Its interval stops including one at a BoolQ weight of 0.0867", "Its interval first excludes one at a BoolQ weight of 0.0867"),
    ("gives no basis for singling out BoolQ.", "gives no basis for a special weight on BoolQ."),
    ("Standardising traits by estimated seed standard deviation gives", "Standardisation of traits by estimated seed standard deviation gives"),
    ("Holding those estimated weights fixed, the wild", "With those estimated weights held fixed, the wild"),
    ("Removing defined traits from the standardised batteries leaves", "The removal of defined traits from the standardised batteries leaves"),
    ("Selecting traits by positive estimated variance can change", "A selection of traits by positive estimated variance can change"),
    ("The resulting ratios of 3.5 and 3.3", "These ratios of 3.5 and 3.3"),
    ("Applying the delete-one-trait jackknife formula produces", "The delete-one-trait jackknife formula produces"),
    ("Comparing the unscaled dispersion instead gives", "A comparison of the unscaled dispersion instead gives"),
    ("Omitting the BoolQ removal value from that calculation gives", "Without the BoolQ removal value, that calculation gives"),
    ("Adding the original jackknife scales and sampling standard errors in quadrature gives",
     "The quadrature sum of the original jackknife scales and sampling standard errors gives"),
    ("0.18 to 1.974, both including one", "0.18 to 1.974, and both include one"),
    ("Repeating that arithmetic without the BoolQ removal value gives", "The same arithmetic without the BoolQ removal value gives"),
    ("report composition sensitivity without treating these scales as", "report composition sensitivity, and we don't treat these scales as"),
    ("Changing trait count also changes", "A change in trait count also changes"),
    ("Comparing 2.75 with 7.10 holds", "A comparison of 2.75 with 7.10 holds"),
    ("and removing both of its benchmarks leaves", "and the removal of both of its benchmarks leaves"),
    ("Rebuilding the numerator and the denominator from the same contrast projections reproduces",
     "When we rebuild the numerator and the denominator from the same contrast projections, they reproduce"),
    ("Holding the number of benchmarks fixed, subsets", "At a fixed number of benchmarks, subsets"),
    ("all ten benchmarks without selecting on scores", "all ten benchmarks and doesn't select on scores"),
    ("A second reweighting, by the inverse", "A second weighting, by the inverse"),
    ("Substituting observed gaps meets", "A substitution of observed gaps meets"),
    ("which is whether correcting their own test", "which is whether a correction of their own test"),
    ("which is the price of estimating a correction that", "which is the price of an estimated correction that"),
    ("and whether buying runs also repairs the miscalibration", "and whether more runs also repair the miscalibration"),
    ("Anyone applying this correction will estimate", "Anyone who applies this correction will estimate"),
    ("most of the error they were trying to remove", "most of the error they wanted to remove"),
    ("Repeating the whole sweep with the accuracy design as the source", "A repeat of the whole sweep with the accuracy design as the source"),
    ("We added this comparison after seeing the full-sample estimates", "We added this comparison after we saw the full-sample estimates"),
    ("Substituting the accuracy simulation dispersion gives", "A substitution of the accuracy simulation dispersion gives"),
    ("we record its shape instead of truncating it", "we record its shape and don't truncate it"),
    ("Rerunning the R6 generator with the same seeds reproduces", "A rerun of the R6 generator with the same seeds reproduces"),
    ("Pooling all three runs of that cell over 60,000 replicates gives 0.946", "All three runs of that cell pooled over 60,000 replicates give 0.946"),
    ("Removing BoolQ leaves both scales above one under all eight", "Without BoolQ both scales stay above one under all eight"),
    ("use the cheapest of those counts without changing a conclusion", "use the cheapest of those counts, and no conclusion changes"),
    ("We picked that construction after seeing the first four cells", "We picked that construction after we saw the first four cells"),
    ("widens to \\ci{1.396}{1.704} while staying above one.", "widens to \\ci{1.396}{1.704} and stays above one."),
    ("Running the same prepivoting inside the four simulated cells", "The same prepivoting inside the four simulated cells"),
    ("Holding the true seed correlation at zero, we swept", "With the true seed correlation held at zero, we swept"),
    ("Regressing the off-diagonal entries of the estimated seed covariance", "A regression of the off-diagonal entries of the estimated seed covariance"),
    ("and adding the shared effect at the share that reproduces", "and the addition of the shared effect at the share that reproduces"),
    ("Permuting $d$ across the items of one group", "A permutation of $d$ across the items of one group"),
    ("because permuting a constant returns the constant", "because a permutation of a constant returns the constant"),
    ("Re-drawing the item half split 200 times moves the estimate", "A total of 200 redraws of the item half split move the estimate"),
    ("it widens the spread without moving the centre", "it widens the spread but doesn't move the centre"),
    ("keeps its advantage there, covering 0.960", "keeps its advantage there, with coverage of 0.960"),
    ("Correcting the cluster-robust $t$ by $G/(G-1)$", "A correction of the cluster-robust $t$ by $G/(G-1)$"),
    ("All four recorded coverages, including the cluster-robust ones of 0.881 and 0.941, land",
     "All four recorded coverages, the cluster-robust ones of 0.881 and 0.941 among them, land"),
    ("matters for interpreting an upper bound", "matters for the interpretation of an upper bound"),
    ("Applying a two-sided 95 percent $t(24)$ critical value to those rounded inputs gives",
     "A two-sided 95 percent $t(24)$ critical value applied to those rounded inputs gives"),
    ("Dropping each benchmark from the proxy in turn leaves", "The removal of each benchmark from the proxy in turn leaves"),
    ("The repair we fixed before seeing its output", "The repair we fixed before we saw its output"),
    ("out of fold, learning each variance, loading, and slope on four recipe folds and applying them to the fifth",
     "out of fold, and we learned each variance, loading, and slope on four recipe folds and applied them to the fifth"),
    ("999 draws, refitting the whole cross-fitted pipeline in each draw, gives", "999 draws, which refits the whole cross-fitted pipeline in each draw, gives"),
    ("stops separating from independence", "no longer separates from independence"),
    ("we read the refusals as gating", "we read the refusals as access gates"),
    ("Resolving all 125 repositories under the released naming instead, every one of the 375 runs resolves without credentials to its own commit, each carrying a config",
     "When we resolve all 125 repositories under the released names instead, every one of the 375 runs resolves without credentials to its own commit, and each commit carries a config"),
    ("came from our own naming, and access", "came from our own repository names, and access"),
    ("names aggregate standard deviation without resolving this scale choice", "names aggregate standard deviation but doesn't resolve this scale choice"),
    ("with hardware and batching changed together.", "with the hardware and the batch setup changed together."),
    ("For each of the 84 ways of choosing three runs", "For each of the 84 ways to choose three runs"),
    ("on the six runs left out", "on the six runs held out"),
    ("Pooling the target across configurations changes", "A target pooled across configurations changes"),
    ("so carrying item noise into the prediction helps", "so the inclusion of item noise in the prediction helps"),
    ("Shared clipping doesn't guarantee", "A shared clip doesn't guarantee"),
    ("Dropping an affected trait from that fold's prediction", "The removal of an affected trait from that fold's prediction"),
    ("and filling its held-out variance with the training-fold estimate gives", "and the training-fold estimate in place of its held-out variance gives"),
    ("and dropping them leaves P3 the best model, with its error falling from 0.0105 to 0.0090, while filling gives",
     "and their removal leaves P3 the best model, with an error that falls from 0.0105 to 0.0090, while the fill gives"),
    ("Subtracting estimated leakage variance", "The subtraction of estimated leakage variance"),
    ("It reports completing this sweep in thirteen seconds", "It reports that this sweep took thirteen seconds"),
    ("the shipped interval after removing each recipe", "the shipped interval after the removal of each recipe"),
    ("The margin interval keeps excluding one under every one of", "The margin interval still excludes one under every one of"),
    ("because dropping the 530M band leaves 1.178", "because the removal of the 530M band leaves 1.178"),
    ("Simulating 10,000 margin-like populations over two runs with separate seeds, and keeping the 9,697 whose full interval excludes one, at least",
     "In 10,000 simulated margin-like populations over two runs with separate seeds, we kept the 9,697 whose full interval excludes one, and at least"),
    ("Holding three runs and raising the recipe count to 50, 100 and 200 takes", "At three runs, a recipe count of 50, 100 and 200 takes"),
    ("has less data standing between it and the estimate", "has less data between it and the estimate"),
    ("Re-estimating on each surviving pair leaves", "A re-estimate on each remaining pair leaves"),
    ("includes one yet stops including it under five", "includes one yet excludes it under five"),
    ("Simulating 10,000 populations whose true ratio is exactly one under accuracy-like noise, again over two runs with separate seeds, and keeping the 9,477 whose full interval includes one, at least",
     "In 10,000 simulated populations whose true ratio is exactly one under accuracy-like noise, again over two runs with separate seeds, we kept the 9,477 whose full interval includes one, and at least"),
    ("sharpened them without changing what they say", "sharpened them and didn't change what they say"),
    ("reads the interval off the resulting spread", "reads the interval from that spread"),
    ("Rescoring the first 150 ARC-Easy documents at 150M from the request file the release itself ships, and forming the same per-byte margins, matches",
     "A rescore of the first 150 ARC-Easy documents at 150M from the request file the release itself ships, with the same per-byte margins, matches"),
    ("blends with dolma 1.7, giving 24 branch cells", "blends with dolma 1.7, which gives 24 branch cells"),
    ("The 1B band is where the release changes both halves of the naming, shipping seeds",
     "In the 1B band the release changes both halves of the names, and it ships seeds"),
    ("rename seventeen of the 25 recipes, writing qc where", "rename seventeen of the 25 recipes, and they write qc where"),
    ("Recommending that fallback obliges us", "Our recommendation of that fallback obliges us"),
    ("Repeating the band-sharing sweep at the accuracy battery's", "A repeat of the band-sharing sweep at the accuracy battery's"),
    ("breaks on accuracy, covering only 0.832", "breaks on accuracy, and it covers only 0.832"),
    ("Five clusters carrying the louder item noise are too few for the bootstrap, and a reader taking the fallback",
     "Five clusters that carry the louder item noise are too few for the bootstrap, and a reader who uses the fallback"),
    ("Widening the battery from four benchmarks to twenty raises", "A wider battery, from four benchmarks to twenty, raises"),
    ("is the one that suffers at two runs, dropping to 0.915.", "suffers at two runs, where it drops to 0.915."),
    ("near 125 by pairing 41 recipes with three bands", "near 125, since it pairs 41 recipes with three bands"),
    ("Spreading it two-fold across the five bands leaves", "A two-fold spread across the five bands leaves"),
    ("tells the same story, holding 0.947 on margins and falling to 0.291 on accuracy", "gives the same result, with 0.947 on margins and 0.291 on accuracy"),
    ("Dropping a tenth, a quarter, a third and a half of the configurations leaves the recipe-clustered interval covering",
     "When we drop a tenth, a quarter, a third and a half of the configurations, the recipe-clustered interval covers"),
    ("A reader missing half their cells keeps a trustworthy interval and loses a quarter of their chances of resolving the question",
     "A reader who lacks half their cells keeps a trustworthy interval and loses a quarter of their chances to resolve the question"),
    ("for the same loss, covering 0.949 complete", "for the same loss, with coverage of 0.949 complete"),
    ("Cutting a tenth, a quarter, a half and then all of the configurations to two seeds leaves",
     "Cuts of a tenth, a quarter, a half and then all of the configurations to two seeds leave"),
    ("four seeds averaging exactly three per configuration", "four seeds with a mean of exactly three per configuration"),
    ("once either dimension grows, reaching 0.933", "once either dimension grows, and it reaches 0.933"),
    ("Sweeping the recipe count over 5, 10, 15, 25, 40 and 60, the wild", "Across recipe counts of 5, 10, 15, 25, 40 and 60, the wild"),
    ("The failure at five clusters is worth naming, since", "The failure at five clusters needs a note, since"),
    ("holds five clusters throughout while covering 0.850", "holds five clusters throughout and covers 0.850"),
    ("the assumptions the generator has been handing the estimator all along", "the assumptions that the generator gave the estimator in every earlier sweep"),
    ("Drawing the latent run effects from a multivariate t leaves", "Latent run effects drawn from a multivariate t leave"),
    ("Giving the 25 recipes variance scales spread over a four-fold and a sixteen-fold range leaves",
     "Variance scales for the 25 recipes, spread over a four-fold and a sixteen-fold range, leave"),
    ("Giving each benchmark the item noise its size implies,", "When each benchmark gets the item noise its size implies,"),
    ("to 14,042 on MMLU, leaves coverage at 0.945", "to 14,042 on MMLU, coverage is 0.945"),
    ("and doubling that spread leaves it at 0.948", "and a doubled spread leaves it at 0.948"),
    ("Crossing three bootstrap weight families", "A cross of three bootstrap weight families"),
    ("Weighting the benchmarks by the item counts the release ships, which run from 500 to 14,042, putting them on a ramp whose last benchmark carries four times the first, and concentrating half the weight on two benchmarks all leave the recipe-clustered interval covering",
     "Three weightings, by the item counts the release ships, which run from 500 to 14,042, on a ramp whose last benchmark carries four times the first, and with half the weight on two benchmarks, all leave the recipe-clustered interval with coverage"),
    ("is therefore asking a question this design", "therefore asks a question this design"),
    ("covers 0.930 while excluding one in only 0.313", "covers 0.930 but excludes one in only 0.313"),
    ("Projecting it onto the positive semidefinite cone clips", "A projection onto the positive semidefinite cone clips"),
    ("three on accuracy, moving the ratios to 1.2438", "three on accuracy, and it moves the ratios to 1.2438"),
    ("Simulating against those measured matrices leaves the recipe-clustered interval covering 0.947",
     "Simulations against those measured matrices leave the recipe-clustered interval with coverage of 0.947"),
    ("since sweeping the true ratio at the margin battery's", "since a sweep of the true ratio at the margin battery's"),
    ("The cell at a true ratio of one is the one worth naming, because", "The cell at a true ratio of one matters most, because"),
    ("one giving a single benchmark 68 percent of the trace, one adding negative links from that benchmark to the other nine, one splitting the battery into two correlated blocks, and one combining dominance",
     "one that gives a single benchmark 68 percent of the trace, one that adds negative links from that benchmark to the other nine, one that splits the battery into two correlated blocks, and one that combines dominance"),
    ("since holding the true band share at zero and drawing the latent effects from a t with five and with three degrees of freedom, and spreading the recipe variances sixteen-fold, leaves",
     "since a true band share of zero, with latent effects drawn from a t with five and with three degrees of freedom and with recipe variances spread sixteen-fold, leaves"),
    ("Lining each configuration's runs up by their batch slot and averaging the run deviations over the 25 recipes of a band leaves a band-shared component untouched while shrinking anything specific to a recipe",
     "If we align each configuration's runs by their batch slot and average the run deviations over the 25 recipes of a band, a band-shared component stays untouched while anything specific to a recipe shrinks"),
    ("Permuting each configuration's runs among its own batch slots", "A permutation of each configuration's runs among its own batch slots"),
    ("while a share sitting at the bound itself", "while a share at the bound itself"),
    ("Repeating the sweep there keeps the test honest about its size", "A repeat of the sweep there confirms the test's size"),
    ("because a band share sitting at 0.044", "because a band share at 0.044"),
    ("the band version's, sweeping the recipe share over", "the band version's, with a sweep of the recipe share over"),
    ("Pooling the two passes over 16,000 replicates gives", "The two passes pooled over 16,000 replicates give"),
    ("Scaling each recipe's residual by one over one minus its leverage, which is the cr3 correction, lifts",
     "The cr3 correction, which scales each recipe's residual by one over one minus its leverage, lifts"),
    ("as the sharing sweeps found, covering between 0.822 and 0.844", "as the sharing sweeps found, with coverage between 0.822 and 0.844"),
    ("at every cell including the corner", "at every cell, the corner among them"),
    ("with a slower agreeing path as the fallback", "and a slower path that gave the same values served as the fallback"),
    ("before the CoQA regrouping", "before we regrouped CoQA"),
    ("and 0.55 of them excluding one against 0.57 there.", "and 0.55 of them exclude one against 0.57 there."),
    ("Pooling the four held-out tasks with the original ten gives", "The four held-out tasks pooled with the original ten give"),
    ("that the protocol committed to reporting", "that the protocol committed us to report"),
    ("Capping at 1,000 items per benchmark leaves", "A cap of 1,000 items per benchmark leaves"),
    ("After seeing that width we added", "After we saw that width, we added"),
    ("can neither confirm nor rule out,", "can neither confirm nor exclude,"),
]
t = P.read_text()
bad = []
for old, new in E:
    n = t.count(old)
    if n != 1:
        bad.append(f"{n}: {old[:90]}")
        continue
    t = t.replace(old, new)
if bad:
    sys.exit("\n".join(bad))
if "--apply" in sys.argv:
    P.write_text(t)
print(f"{len(E)} edits {'applied' if '--apply' in sys.argv else 'checked'}")
