"""ASD-STE100 pass on the appendices, rule 3 (-ing verb forms become finite verbs or nouns).
usage: python3 work/goal/edits_ste_app.py [--apply]"""
import sys
from pathlib import Path

D = Path(__file__).resolve().parents[2] / "deliverables"
A = [
    ("reserving a seed-only interpretation for designs with matching training conditions.",
     "and we keep a seed-only interpretation for designs with matched training conditions."),
    ("A run can perform differently on particular items without changing its expected score over an item population,",
     "A run can perform differently on particular items and keep its expected score over an item population,"),
    ("predicts the second after supplying marginal run variances.", "predicts the second once we supply marginal run variances."),
    ("Expanding $d^A_{rj}d^B_{rk}$ then removes its error cross terms in expectation, leaving",
     "The expansion of $d^A_{rj}d^B_{rk}$ then removes its error cross terms in expectation and leaves"),
    ("Summing across runs and dividing by $R-1$ gives the unbiased covariance moment.",
     "A sum across runs divided by $R-1$ gives the unbiased covariance moment."),
    ("match the google/boolq validation split exactly, giving 2,938 passages with",
     "match the google/boolq validation split exactly, and they give 2,938 passages with"),
]
B = [
    ("Excluding the 26 severely truncated configurations gives 1.276 with interval",
     "Without the 26 severely truncated configurations, margin inflation is 1.276 with interval"),
    ("Permuting that share within each size over 4,999 draws gives", "A permutation of that share within each size over 4,999 draws gives"),
    ("We chose these subsets after seeing the full-sample estimates,", "We chose these subsets after we saw the full-sample estimates,"),
    ("The planning document proposed estimating reliability on eight screening recipes before inspecting seventeen estimation recipes.",
     "The planning document proposed that we estimate reliability on eight screening recipes before we inspect seventeen estimation recipes."),
    ("Recomputing the per-trait information ratios gives a median of 1.608, a minimum of 1.571, and a maximum of 1.732, reproducing the three figures the pipeline summary reported without releasing the ratios themselves.",
     "A recomputation of the per-trait information ratios gives a median of 1.608, a minimum of 1.571, and a maximum of 1.732, the same three figures the pipeline summary reported, although the summary didn't release the ratios themselves."),
    ("Interpolating the N1 simulation grid gives dispersion", "Interpolation of the N1 simulation grid gives dispersion"),
    ("don't recompute power from the estimated effect after observing the results.", "don't recompute power from the estimated effect after we saw the results."),
    ("because multiplying a margin by a positive factor leaves its sign unchanged.",
     "because the multiplication of a margin by a positive factor leaves its sign unchanged."),
    ("lists each criterion with its outcome without treating the document as verified preregistration.",
     "lists each criterion with its outcome, and we don't treat the document as verified preregistration."),
    ("while treating each evaluated model as fixed,", "with each evaluated model treated as fixed,"),
    ("by Stouffer's method, noting that positive task correlation would make the combination conservative, without estimating that correlation.",
     "by Stouffer's method, and they note that positive task correlation would make the combination conservative but don't estimate that correlation."),
    ("We read this as the composition sensitivity reappearing at size resolution, and not as independent support for the pooled estimate, because the full-battery sweep already names BoolQ as the benchmark pulling hardest toward one.",
     "We read this as the composition sensitivity that reappears at size resolution, and not as independent support for the pooled estimate, because the full-battery sweep already names BoolQ as the benchmark that pulls hardest toward one."),
    ("It buys definedness on that band by paying coverage.", "It buys definedness on that band at a cost in coverage."),
    ("The leverage correction repairs more, lifting the margin band to 0.942 at three runs",
     "The leverage correction repairs more, and it lifts the margin band to 0.942 at three runs"),
    ("in a thin cell without giving a better interval", "in a thin cell but doesn't give a better interval"),
    ("reproduces the full estimate to four decimal places before retaining 54 of the 90 ordered off-diagonal pairs.",
     "reproduces the full estimate to four decimal places and then retains 54 of the 90 ordered off-diagonal pairs."),
    ("and below the 1.113 that a uniform shared item component carrying the whole margin excess alone,",
     "and below the 1.113 that a uniform shared item component with the whole margin excess alone,"),
    ("Excluding BoolQ gives a cross-format margin diagnostic of 1.006", "Without BoolQ, the cross-format margin diagnostic is 1.006"),
    ("Among the nine traits with defined margin correlations, excluding WinoGrande, the mean correlation",
     "Among the nine traits with defined margin correlations, which leave out WinoGrande, the mean correlation"),
    ("Excluding ARC-Easy and ARC-Challenge from the multiple-choice block leaves inflation of 1.479",
     "Without ARC-Easy and ARC-Challenge in the multiple-choice block, inflation is 1.479"),
    ("Equal variances with the same two correlations give 1.803, showing how much of the gap",
     "Equal variances with the same two correlations give 1.803, which shows how much of the gap"),
    ("The implementation fills these entries with zero before differencing, including undefined diagonal entries compared with unit diagonals in $R_P$.",
     "The implementation fills these entries with zero before it takes differences, and that includes undefined diagonal entries compared with unit diagonals in $R_P$."),
    ("Repairing only those diagonals gives distances of 5.499 and 6.339.", "A repair of only those diagonals gives distances of 5.499 and 6.339."),
    ("Restricting the comparison to jointly defined entries gives 4.374 and 4.593,",
     "If we restrict the comparison to jointly defined entries, the distances are 4.374 and 4.593,"),
    ("Each model receives the held-out marginal seed standard deviations, isolating the correlation component.",
     "Each model receives the held-out marginal seed standard deviations, so the comparison isolates the correlation component."),
    ("Before fitting any model we clip negative variance estimates,", "Before we fit any model we clip negative variance estimates,"),
    ("Before computing any contrast we fixed eight paired differences", "Before we computed any contrast we fixed eight paired differences"),
    ("refit the whole comparison in each draw, treating the designed recipes as exchangeable clusters and absorbing fold-partition variation.",
     "refit the whole comparison in each draw, with the designed recipes treated as exchangeable clusters, and that absorbs fold-partition variation."),
    ("so the comparison bounds detectable gains without calibrating the ranking above.",
     "so the comparison bounds detectable gains but doesn't calibrate the ranking above."),
    ("imply that the off-diagonal terms involving BoolQ are negative, summing to about",
     "imply that the off-diagonal terms with BoolQ are negative and sum to about"),
    ("in seven steps to 0.0533, raising the other nine weights together so the battery still sums to one.",
     "in seven steps to 0.0533 and raised the other nine weights together so the battery still sums to one."),
    ("Its interval stops including one at a BoolQ weight of 0.0867,", "Its interval excludes one at a BoolQ weight of 0.0867 and below,"),
    ("because the release gives no basis for singling out BoolQ.", "because the release gives no basis for a special BoolQ weight."),
    ("gives ranges of 0.15 to 2.33 and 0.18 to 1.974, both including one.", "gives ranges of 0.15 to 2.33 and 0.18 to 1.974, and both include one."),
    ("and report composition sensitivity without treating these scales as an identified decomposition of total uncertainty.",
     "and report composition sensitivity, and we don't treat these scales as an identified decomposition of total uncertainty."),
    ("whose interval has an undefined endpoint count as not excluding it.", "whose interval has an undefined endpoint count as draws that don't exclude it."),
    ("changes the weights of all ten benchmarks without selecting on scores.", "changes the weights of all ten benchmarks and doesn't select on scores."),
    ("Deleting recipes instead, two of the 25 at a time, leaves a margin interval", "The deletion of recipes instead, two of the 25 at a time, leaves a margin interval"),
    ("Comparing squared linearised standard errors, using 0.045 against 0.093 on margins and 0.038 against 0.052 on accuracy, gives ratios of 0.23 and 0.53.",
     "A comparison of squared linearised standard errors, with 0.045 against 0.093 on margins and 0.038 against 0.052 on accuracy, gives ratios of 0.23 and 0.53."),
    ("and removing that shared change lowers the accuracy ratio to 1.279,", "and the removal of that shared change lowers the accuracy ratio to 1.279,"),
    ("We added this comparison after seeing the full-sample estimates.", "We added this comparison after we saw the full-sample estimates."),
    ("one in ten, one in twenty and one in a hundred, giving 0.896, 0.951 and 0.990,", "one in ten, one in twenty and one in a hundred, and it gave 0.896, 0.951 and 0.990,"),
    ("We picked it after seeing the first four cells.", "We picked it after we saw the first four cells."),
    ("A share carrying the whole observed excess would be", "A share with the whole observed excess would be"),
    ("is 0.420, carrying 0.319 of the margin excess on the inflation scale", "is 0.420, and it carries 0.319 of the margin excess on the inflation scale"),
    ("Adding a 0.124 share to the observed products instead gives", "The addition of a 0.124 share to the observed products instead gives"),
    ("Re-drawing the item half split 200 times in that kernel,", "When we redraw the item half split 200 times in that kernel,"),
    ("separately from the fifty re-splits of the primary run, gives a margin range of 1.242 to 1.254",
     "separately from the fifty re-splits of the primary run, the margin range is 1.242 to 1.254"),
    ("Item-level structure does survive and widens the spread without moving the centre.",
     "Item-level structure does survive, and it widens the spread but leaves the centre in place."),
    ("listed as 610 in the release summary, including WikiText-103 and OpenWebText validation perplexity.",
     "listed as 610 in the release summary, with WikiText-103 and OpenWebText validation perplexity."),
    ("The repair we fixed before seeing its output standardises", "The repair we fixed before we saw its output standardises"),
    ("The adjusted margin estimate therefore stops separating from independence.", "The adjusted margin estimate therefore no longer separates from independence."),
    ("names aggregate standard deviation without resolving this scale choice,", "names aggregate standard deviation but doesn't resolve this scale choice,"),
    ("at five sizes, with the excess ratio moving from 1.69592 to 1.07393.", "at five sizes, and the excess ratio moves from 1.69592 to 1.07393."),
    ("with each configuration as its own cluster, giving margin sets of 0 to 2.106", "with each configuration as its own cluster, and that gives margin sets of 0 to 2.106"),
    ("For each of the 84 ways of choosing three runs,", "For each of the 84 ways to choose three runs,"),
    ("The 84 splits share runs, making these descriptive differences without an interval.",
     "The 84 splits share runs, so these are descriptive differences without an interval."),
    ("at 0.0063 each under dropping and at 0.0039 and 0.0045 under training fill,", "at 0.0063 each under the drop rule and at 0.0039 and 0.0045 under training fill,"),
    ("On accuracy, dropping leaves P3 the best model at 0.0090 and filling gives P1 and P3 errors",
     "On accuracy, the drop rule leaves P3 the best model at 0.0090 and the fill rule gives P1 and P3 errors"),
    ("of Section~\\ref{sec:family} after fixing them,", "of Section~\\ref{sec:family} after we fixed them,"),
    ("A jackknife that drops a seed's term without recentring the others understates", "A jackknife that drops a seed's term but doesn't recentre the others understates"),
    ("without cross-half correction or uncertainty intervals, limiting comparison with the corrected primary estimator.",
     "without cross-half correction or uncertainty intervals, and that limits comparison with the corrected primary estimator."),
    ("We also recomputed our interval after deleting each recipe, recipe pair, size band and benchmark in turn.",
     "We also recomputed our interval after the deletion of each recipe, recipe pair, size band and benchmark in turn."),
    ("The margin interval keeps excluding one under every recipe, pair and benchmark deletion.",
     "The margin interval excludes one under every recipe, pair and benchmark deletion."),
    ("Re-estimation on each surviving pair of runs leaves the margin estimate at 1.256, 1.242 and 1.235, all excluding one, while the accuracy estimate sits at 1.084, 1.114 and 1.030, with none of the three intervals excluding one.",
     "Re-estimation on each remaining pair of runs leaves the margin estimate at 1.256, 1.242 and 1.235, and all three exclude one, while the accuracy estimate sits at 1.084, 1.114 and 1.030, and none of its three intervals excludes one."),
    ("Its full-battery interval includes one yet stops including it under five of the 25 recipe deletions,",
     "Its full-battery interval includes one yet excludes it under five of the 25 recipe deletions,"),
    ("and raising the recipe count to 50, 100 and 200 at three runs takes that to", "and a recipe count of 50, 100 and 200 at three runs takes that to"),
    ("with a slower agreeing path as the fallback.", "with a slower path that agrees as the fallback."),
    ("once it became a primary task, rewriting the group field on 932 rows.", "once it became a primary task, and this rewrote the group field on 932 rows."),
    ("the same count as at all sizes, and 0.55 of them excluding one against 0.57 there.",
     "the same count as at all sizes, and 0.55 of them exclude one against 0.57 there."),
    ("Removing CoQA lowers held-out margin inflation to 1.090 with interval \\ci{0.990}{1.181}, and removing any other task leaves it between 1.120 and 1.213.",
     "Without CoQA, held-out margin inflation falls to 1.090 with interval \\ci{0.990}{1.181}, and without any other task it stays between 1.120 and 1.213."),
    ("alongside the all-size curve that the protocol committed to reporting.", "alongside the all-size curve that the protocol committed us to report."),
    ("After seeing that width we added noise levels", "After we saw that width we added noise levels"),
    ("when its gap exceeds two corrected standard errors, again leaving the pair out.", "when its gap exceeds two corrected standard errors, again without the pair."),
    ("resamples the pair outcomes without re-estimating the standard deviations.", "resamples the pair outcomes and doesn't re-estimate the standard deviations."),
    ("We computed both with the same estimator, feeding it the full-bank scores as both halves for the replicate value,",
     "We computed both with the same estimator, which took the full-bank scores as both halves for the replicate value,"),
    ("Regenerating the split requires the recorded item ordering and randomisation specification, without downloading the full tarballs.",
     "A regeneration of the split requires the recorded item ordering and randomisation specification, and it doesn't need a download of the full tarballs."),
    ("Writing $q_\\alpha$ for the empirical quantile of these statistics, the interval on $\\theta$ is",
     "With $q_\\alpha$ the empirical quantile of these statistics, the interval on $\\theta$ is"),
    ("requires at least $\\max(100,0.9B)$ surviving draws before reporting an interval.",
     "requires at least $\\max(100,0.9B)$ valid draws before it reports an interval."),
    ("removes the shared performance mean before forming cross-half products.", "removes the shared performance mean before we form cross-half products."),
    ("Applying one joint permutation to all traits preserves cross-trait pairing and therefore doesn't generate this independence null.",
     "One joint permutation of all traits preserves the cross-trait pairs and therefore doesn't generate this independence null."),
    ("used one Kaggle CPU core for Arm 1, reporting 6.0 hours for estimation and null checks.",
     "used one Kaggle CPU core for Arm 1 and reported 6.0 hours for estimation and null checks."),
    ("Four sensitivity tasks took another 1.6 hours, including gain calibration and fifty re-splits",
     "Four sensitivity tasks took another 1.6 hours, with gain calibration and fifty re-splits"),
    ("streams 25 monolithic tarballs totalling 122.9 GB while keeping peak disk use below 10 GB.",
     "streams 25 monolithic tarballs, 122.9 GB in total, and keeps peak disk use below 10 GB."),
    ("Changing the budget changes batch grouping", "A change to the budget changes batch grouping"),
    ("expose some inconsistencies without replacing a release-side audit.", "expose some inconsistencies but don't replace a release-side audit."),
    ("uses released per-item outputs without recomputing forward passes.", "uses released per-item outputs and doesn't recompute forward passes."),
    ("annihilates the all-ones vector, making raw and centred inputs equivalent under projection.",
     "annihilates the all-ones vector, so raw and centred inputs are equivalent under projection."),
    ("on both halves, addressing centring errors without testing measurement or exchangeability assumptions.",
     "on both halves, and they catch centring errors but don't test measurement or exchangeability assumptions."),
]


def run(path, edits):
    t = path.read_text()
    for old, new in edits:
        n = t.count(old)
        if n != 1:
            sys.exit(f"{path.name}: expected one match, found {n}: {old[:90]}")
        t = t.replace(old, new)
    if "--apply" in sys.argv:
        path.write_text(t)


run(D / "appendix_a.tex", A)
run(D / "appendices_bcd.tex", B)
print(f"{len(A) + len(B)} edits {'applied' if '--apply' in sys.argv else 'checked'}")
