r"""Whole-text flow read of the Scan 104 main text (done by the main session after three
Opus readers failed on API overload). Five merged sentences are split back at their
original boundary: an X-and-Y-and-Z chain, a sentence carrying the same appendix pointer
twice, a 55-word two-step procedure, and two "where ..., while ..." chains in which
"where" joins a result to a removal rather than to a place. Each pair differs from its
original only by a comma turned into a full stop, the dropped connective and one capital,
verified by character diff, so these were applied while the Opus refuter was unavailable
(API 529 outage on 2026-09-21)."""
EDITS = [
("We recovered the 2,938 passages behind BoolQ's 3,270 questions from the release's request files, and assigning each passage whole to one half changes the two estimates by $-0.0002$ and $-0.0001$ on average across fifty re-splits, and the BoolQ diagonal moves by 0.03\\% and 0.15\\% (Appendix~\\ref{app:derivations}).",
 "We recovered the 2,938 passages behind BoolQ's 3,270 questions from the release's request files, and assigning each passage whole to one half changes the two estimates by $-0.0002$ and $-0.0001$ on average across fifty re-splits. The BoolQ diagonal moves by 0.03\\% and 0.15\\% (Appendix~\\ref{app:derivations})."),
('Across the nine defined margin traits our estimated correlations track scoring format, averaging 0.624 within formats and 0.007 across them (Figure~\\ref{fig:covariance} in Appendix~\\ref{app:supplementary}), and cross-format off-diagonal covariance alone gives diagnostic inflation of 0.921 with interval \\ci{0.801}{1.035} against 1.244 for the full matrix (Appendix~\\ref{app:supplementary}).',
 'Across the nine defined margin traits our estimated correlations track scoring format, averaging 0.624 within formats and 0.007 across them (Figure~\\ref{fig:covariance} in Appendix~\\ref{app:supplementary}). Cross-format off-diagonal covariance alone gives diagnostic inflation of 0.921 with interval \\ci{0.801}{1.035} against 1.244 for the full matrix (Appendix~\\ref{app:supplementary}).'),
("At each size below 1B we called a pair of recipes when their aggregate gap exceeded two standard errors, computed either under independence or with the estimated covariance, leaving the pair out of both estimates, and we scored each call against the pair's ordering at 1B whenever that ordering itself cleared two corrected standard errors.",
 "At each size below 1B we called a pair of recipes when their aggregate gap exceeded two standard errors, computed either under independence or with the estimated covariance, leaving the pair out of both estimates. We scored each call against the pair's ordering at 1B whenever that ordering itself cleared two corrected standard errors."),
('We report the wild interval because it covers well across the twelve populations that Table~\\ref{tab:coverage} in the appendix lists, where a 2,000-replicate simulation per population, using the same 4,999 draws, gives wild bootstrap coverage of 0.928 to 0.954, while the configuration percentile bootstrap drops to 0.872 under recipe-shared effects.',
 'We report the wild interval because it covers well across the twelve populations that Table~\\ref{tab:coverage} in the appendix lists. A 2,000-replicate simulation per population, using the same 4,999 draws, gives wild bootstrap coverage of 0.928 to 0.954, while the configuration percentile bootstrap drops to 0.872 under recipe-shared effects.'),
('We find that BoolQ dominates the battery, contributing 68\\% of the margin covariance trace and 84\\% of the accuracy trace, where removing it raises margin inflation to 1.786 with interval \\ci{1.689}{1.877}, and accuracy inflation to 1.558 with interval \\ci{1.412}{1.687}, while removing CommonsenseQA instead gives inflation estimates of 1.096 and 1.014.',
 'We find that BoolQ dominates the battery, contributing 68\\% of the margin covariance trace and 84\\% of the accuracy trace. Removing it raises margin inflation to 1.786 with interval \\ci{1.689}{1.877}, and accuracy inflation to 1.558 with interval \\ci{1.412}{1.687}, while removing CommonsenseQA instead gives inflation estimates of 1.096 and 1.014.'),
]
