r"""Rhythm pass on the Scan 104 main text: merges of adjacent short sentences,
four sentence-initial However reversals moved into clauses, three pipeline
steps in the passive. Numbers, labels and claims are unchanged; the style gate
in work/style_check.py checks that on every pair. Four Opus 5 refuters reviewed the first draft of 55 pairs before
application; six pairs were dropped on their refutations and nine repaired. The refuter
repair of the checkpoint-step pair was declined because the claim it said was dropped
still appears verbatim later in the same paragraph."""
EDITS = [
('On per-byte margins the battery average spreads more than independence predicts. Its standard deviation is 1.244 times what independence predicts, with interval \\ci{1.143}{1.338} and lower endpoint 1.095 under a test inversion added later, and every recipe, recipe-pair and benchmark deletion leaves an interval that excludes one.',
 'On per-byte margins the battery average spreads more than independence predicts, with a standard deviation 1.244 times the independent value (interval \\ci{1.143}{1.338}, lower endpoint 1.095 under a test inversion added later), and every recipe, recipe-pair and benchmark deletion leaves an interval that excludes one.'),
("Covariance adds the off-diagonal terms to that variance. Assuming independence therefore weakens a comparison's error control.",
 "Covariance adds the off-diagonal terms to that variance, and assuming independence therefore weakens a comparison's error control."),
('We estimate item-general covariance from two disjoint item halves per benchmark. Within each configuration, we centre both half scores across replicate runs and take their cross-half products.',
 'We estimate item-general covariance from two disjoint item halves per benchmark, centring both half scores across the replicate runs within each configuration and taking their cross-half products.'),
('with 25 data recipes and five model sizes that each have three released replicates. Those 125 configurations supply 375 runs across ten benchmarks.',
 'with 25 data recipes and five model sizes that each have three released replicates, and those 125 configurations supply 375 runs across ten benchmarks.'),
('We average items within each benchmark, with MMLU macro-averaged over its 57 subjects, and we denote',
 'Items are averaged within each benchmark, with MMLU macro-averaged over its 57 subjects, and we denote'),
('A half-specific mean lets the two item sets differ in difficulty. The component $E_{crj}$ is the run deviation shared by the two item populations, with the term $\\varepsilon^H_{crj}$ carrying the remaining item-dependent variation.',
 'A half-specific mean lets the two item sets differ in difficulty, the component $E_{crj}$ is the run deviation shared by the two item populations, and the term $\\varepsilon^H_{crj}$ carries the remaining item-dependent variation.'),
('We centre each half score across the replicate runs, defining $d^H_{crj}',
 'Each half score is then centred across the replicate runs, which defines $d^H_{crj}'),
('We sum each statistic across configurations before dividing, which gives',
 'Each statistic is summed across configurations before the division, which gives'),
("Our $K_{\\mathrm{eff}}$ compares this battery against independent benchmarks of the same average variance. Note that it doesn't count independent information sources.",
 "Note that our $K_{\\mathrm{eff}}$ compares this battery against independent benchmarks of the same average variance and doesn't count independent information sources."),
("At an illustrative accuracy of $p=0.35$ this model gives about 1.66. Its minimum is $\\pi/2$, which means the planned lower threshold of 1.4 for per-trait ratios couldn't falsify the model (prediction eight of the plan, Appendix~\\ref{app:design}). However, the calculation describes only the assumed location-shift model. It doesn't show an empirical information advantage for arbitrary margin distributions.",
 "At an illustrative accuracy of $p=0.35$ this model gives about 1.66, and its minimum is $\\pi/2$, which means the planned lower threshold of 1.4 for per-trait ratios couldn't falsify the model (prediction eight of the plan, Appendix~\\ref{app:design}). Yet the calculation describes only the assumed location-shift model and doesn't show an empirical information advantage for arbitrary margin distributions."),
('We also report a configuration percentile bootstrap that resamples both sums but ignores recipe dependence. Neither interval width alone identifies a design effect.',
 'We also report a configuration percentile bootstrap that resamples both sums but ignores recipe dependence, and neither interval width alone identifies a design effect.'),
('Cross-half error correlation of 0.1 biases the estimate downward by 0.014 at margin-like noise and 0.016 at accuracy-like noise. Under accuracy-like item noise the null population carries a downward bias of 0.011.',
 'Cross-half error correlation of 0.1 biases the estimate downward by 0.014 at margin-like noise and 0.016 at accuracy-like noise, and under accuracy-like item noise the null population carries a downward bias of 0.011.'),
('Recipe influence on the margin estimate is concentrated. The participation ratio is 3.08 across the 25 recipes, one recipe holds 0.520 of the squared influence, and removing that recipe moves the estimate by 0.037.',
 'Recipe influence on the margin estimate is concentrated, with a participation ratio of 3.08 across the 25 recipes and one recipe holding 0.520 of the squared influence, and removing that recipe moves the estimate by 0.037.'),
('In each configuration we select the largest checkpoint step available for all three runs. We find that the shared step falls well short of the final step for the larger default runs.',
 'In each configuration we select the largest checkpoint step available for all three runs.'),
('At 750M the default runs stop well short of their released final models. However, the auxiliary runs sit close to their own final steps in every 750M configuration but one.',
 'At 750M the default runs stop well short of their released final models, whereas the auxiliary runs sit close to their own final steps in every 750M configuration but one.'),
('At the adjacent earlier shared step the accuracy interval is \\ci{1.044}{1.210} and excludes one (Appendix~\\ref{app:checkpoint}). On the 123 configurations that share an adjacent step, the paired change',
 'At the adjacent earlier shared step the accuracy interval is \\ci{1.044}{1.210} and excludes one (Appendix~\\ref{app:checkpoint}), and on the 123 configurations that share an adjacent step, the paired change'),
("We find that no estimation set reaches the plan's thresholds of 1.349 and 1.40. An enumeration over the $\\binom{25}{17}=1{,}081{,}575$ possible estimation sets produces",
 "We find that no estimation set reaches the plan's thresholds of 1.349 and 1.40, since an enumeration over the $\\binom{25}{17}=1{,}081{,}575$ possible estimation sets produces"),
("an entry of 1.296 and an eigenvalue of $-0.55$. Thus it isn't a valid correlation matrix without further regularisation.",
 "an entry of 1.296 and an eigenvalue of $-0.55$, and thus it isn't a valid correlation matrix without further regularisation."),
('and lowers the aggregate standard deviation on both scales. A larger factor accompanies a less variable average.',
 'and lowers the aggregate standard deviation on both scales, and a larger factor accompanies a less variable average.'),
('Item-level sharing accounts for about 0.001 of the margin estimate and 0.002 of the accuracy estimate. However, an effect carried by every item of a benchmark survives this permutation untouched.',
 'Item-level sharing accounts for about 0.001 of the margin estimate and 0.002 of the accuracy estimate, but an effect carried by every item of a benchmark survives this permutation untouched.'),
('The test passes only if the lower 95\\% limit exceeds one. Table~\\ref{tab:heldout} reports the test at its registered scope.',
 'The test passes only if the lower 95\\% limit exceeds one, and Table~\\ref{tab:heldout} reports the test at its registered scope.'),
("Gain adjustment doesn't reduce margin inflation, leaving it at 1.275. The plan instead predicted more than 0.70 of the accuracy excess surviving that adjustment.",
 "Gain adjustment doesn't reduce margin inflation, leaving it at 1.275, whereas the plan predicted more than 0.70 of the accuracy excess surviving that adjustment."),
('on a five-size rescore. Accuracy inflation there is 1.711 with interval \\ci{0.869}{2.428} and stays unbounded under test inversion (Appendix~\\ref{app:transport}).',
 'on a five-size rescore, and accuracy inflation there is 1.711 with interval \\ci{0.869}{2.428} and stays unbounded under test inversion (Appendix~\\ref{app:transport}).'),
('That changes the share of wrong calls by at most 0.009, from rates between 0.029 and 0.070. Every recipe-bootstrap interval for that change reaches zero (Table~\\ref{tab:decision}).',
 'That changes the share of wrong calls by at most 0.009, from rates between 0.029 and 0.070, and every recipe-bootstrap interval for that change reaches zero (Table~\\ref{tab:decision}).'),
("and measure each source's variance in five case studies. However, we apply covariance accounting across benchmarks within a replicate run.",
 "and measure each source's variance in five case studies, whereas we apply covariance accounting across benchmarks within a replicate run."),
("where simulated coverage is 0.941 at a share of 0.05. That test's power is only 0.490 at the bound.",
 "where simulated coverage is 0.941 at a share of 0.05, and that test's power is only 0.490 at the bound."),
('For practice we recommend paired replicate scores across the chosen battery and a benchmark-removal sensitivity check. Paired scores give the aggregate seed standard deviation directly.',
 'For practice we recommend paired replicate scores across the chosen battery, which give the aggregate seed standard deviation directly, and a benchmark-removal sensitivity check.'),
('scored on the same checkpoints at 530M, 750M, and 1B. The registered rule required the lower interval limit for held-out margin inflation to exceed one.',
 'scored on the same checkpoints at 530M, 750M, and 1B, with a registered rule requiring the lower interval limit for held-out margin inflation to exceed one.'),
('We register a test on unseen tasks, and it fails at its registered scope. The held-out margin interval runs 0.626 wide against 0.343 for the original ten benchmarks on the same runs, where the rule reads the lower limit.',
 'We register a test on unseen tasks, and it fails at its registered scope, where the held-out margin interval runs 0.626 wide against 0.343 for the original ten benchmarks on the same runs and the rule reads the lower limit.'),
('Item noise shared across benchmarks and repeated across halves would also enter the numerator. We therefore read our estimate',
 'Item noise shared across benchmarks and repeated across halves would also enter the numerator, and we therefore read our estimate'),
('and either pooled sum can be nonpositive in a finite sample. We therefore use calibration simulations to check finite-sample behaviour in specified populations.',
 'and either pooled sum can be nonpositive in a finite sample, which is why we use calibration simulations to check finite-sample behaviour in specified populations.'),
('that Table~\\ref{tab:coverage} in the appendix lists. A 2,000-replicate simulation per population, using the same 4,999 draws, gives',
 'that Table~\\ref{tab:coverage} in the appendix lists, where a 2,000-replicate simulation per population, using the same 4,999 draws, gives'),
('since an unbiased moment estimate can be negative near zero. Deleting a benchmark because we saw its negative estimate would change both the selection rule and the estimand.',
 'since an unbiased moment estimate can be negative near zero and deleting a benchmark because we saw its negative estimate would change both the selection rule and the estimand.'),
('contributing 68\\% of the margin covariance trace and 84\\% of the accuracy trace. Removing BoolQ raises margin inflation to 1.786 with interval \\ci{1.689}{1.877}, and accuracy inflation to 1.558 with interval \\ci{1.412}{1.687}, and removing CommonsenseQA instead gives',
 'contributing 68\\% of the margin covariance trace and 84\\% of the accuracy trace, where removing it raises margin inflation to 1.786 with interval \\ci{1.689}{1.877}, and accuracy inflation to 1.558 with interval \\ci{1.412}{1.687}, while removing CommonsenseQA instead gives'),
('on average across fifty re-splits. The BoolQ diagonal moves by 0.03\\% and 0.15\\% (Appendix~\\ref{app:derivations}).',
 'on average across fifty re-splits, and the BoolQ diagonal moves by 0.03\\% and 0.15\\% (Appendix~\\ref{app:derivations}).'),
('is 1.217 with interval \\ci{0.872}{1.498}. The original ten on the same runs give 1.240 with interval \\ci{1.054}{1.397} and pass it, a comparison we fixed',
 'is 1.217 with interval \\ci{0.872}{1.498}, while the original ten on the same runs give 1.240 with interval \\ci{1.054}{1.397} and pass it, a comparison we fixed'),
('after the weekly GPU quota ran out. The scorer and settings match apart from torch 2.14.0 in place of 2.10.0, and our batch check passed by more than a factor of ten.',
 'after the weekly GPU quota ran out, and the scorer and settings match apart from torch 2.14.0 in place of 2.10.0, with our batch check passing by more than a factor of ten.'),
('close to the observed held-out width. At that level the rule passes in 0.262 of replicates at a true 1.244 against a size of 0.025.',
 'close to the observed held-out width, and at that level the rule passes in 0.262 of replicates at a true 1.244 against a size of 0.025.'),
('(Figure~\\ref{fig:covariance} in Appendix~\\ref{app:supplementary}). Cross-format off-diagonal covariance alone gives',
 '(Figure~\\ref{fig:covariance} in Appendix~\\ref{app:supplementary}), and cross-format off-diagonal covariance alone gives'),
('for a half-point gap against 0.229 under independence. Of the 1,500 observed same-size gaps, 455 fall below',
 'for a half-point gap against 0.229 under independence, and of the 1,500 observed same-size gaps, 455 fall below'),
('count effective independent tests to adjust thresholds. We instead estimate the run covariance of a fixed battery (Appendix~\\ref{app:design}).',
 'count effective independent tests to adjust thresholds, whereas we estimate the run covariance of a fixed battery (Appendix~\\ref{app:design}).'),
("of item-noise variance reproduce 1.244 and 1.078. We haven't measured that component and can't separate it from seed covariance with the diagnostics we ran (Appendix~\\ref{app:calibration}).",
 "of item-noise variance reproduce 1.244 and 1.078, an item effect we haven't measured and can't separate from seed covariance with the diagnostics we ran (Appendix~\\ref{app:calibration})."),
('and those average 0.007 with a diagnostic of 0.921. That check constrains a uniform component and leaves one that follows scoring format untouched.',
 'and those average 0.007 with a diagnostic of 0.921, a check that constrains a uniform component and leaves one that follows scoring format untouched.'),
('across every recipe inside a size band. A run effect following the band would break that choice',
 'across every recipe inside a size band, and a run effect following the band would break that choice'),
('returns the simulated false-positive rate from 0.113 to 0.051. Carried to a battery whose own ratio is 1.5, it leaves the error at 0.101.',
 'returns the simulated false-positive rate from 0.113 to 0.051, and carried to a battery whose own ratio is 1.5, it leaves the error at 0.101.'),
('The accuracy interval no longer includes one under five of the 25 recipe removals, removal of the 750M band, and removal of WinoGrande or BoolQ. A simulation at the fitted accuracy cell excludes one in 0.111 of replicates and would have detected a true ratio of 1.10 in only 0.135 of them.',
 'The accuracy interval no longer includes one under five of the 25 recipe removals, removal of the 750M band, and removal of WinoGrande or BoolQ, while a simulation at the fitted accuracy cell excludes one in 0.111 of replicates and would have detected a true ratio of 1.10 in only 0.135 of them.'),
("leaving the pair out of both estimates. We scored each call against the pair's ordering at 1B whenever that ordering itself cleared two corrected standard errors.",
 "leaving the pair out of both estimates, and we scored each call against the pair's ordering at 1B whenever that ordering itself cleared two corrected standard errors."),
('and Table~\\ref{tab:notation} in Appendix~\\ref{app:derivations} collects the symbols of the cross-half construction and its empirical diagnostics.',
 'and Table~\\ref{tab:notation} in Appendix~\\ref{app:derivations} collects the symbols of the construction and its diagnostics.'),
('We now turn to mechanism, calibration, and outside evidence. Across the nine defined margin traits our estimated correlations track scoring format, averaging 0.624 within formats and 0.007 across them',
 'Across the nine defined margin traits our estimated correlations track scoring format, averaging 0.624 within formats and 0.007 across them'),

# fourth wave, two merges added after the refuter round (both neutral joins, one However moved into a but-clause)
("and 0.512 for our decomposition (Appendix~\\ref{app:transport}). Our estimated ratio is therefore a measurement of this battery",
 "and 0.512 for our decomposition (Appendix~\\ref{app:transport}), and our estimated ratio is therefore a measurement of this battery"),
("A residual-scaled wild interval covers 0.943 to 0.958 there and moves neither interval across one. However, because we chose it after seeing four of the cells, we report the shipped interval throughout (Appendix~\\ref{app:calibration}).",
 "A residual-scaled wild interval covers 0.943 to 0.958 there and moves neither interval across one, but because we chose it after seeing four of the cells we report the shipped interval throughout (Appendix~\\ref{app:calibration})."),
]
